chart/urls.py
from django.urls import path

from . import views
app_name = "chart"

urlpatterns = [
    path('', views.index, name='index'),
]

loginauth/urls.py
from django.urls import path
from . import views

app_name = 'loginauth'

urlpatterns = [
    path('', views.redirect_view),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('create_user/', views.signup, name='create_user'),
]

media/urls.py
from django.urls import path

from . import views

app_name = "media"
 
urlpatterns = [
    path('', views.index, name='list'),
    path('profile/', views.profile, name='profile'),
    path('createview',views.PostView.as_view(),name = 'createview')
    # path('/<string:user_id>/<int:content_id>', views.index, name='index'),
    # path('', views.index, name='index'),
]

trademedia/urls.py
from django.contrib import admin
from django.urls import path,include
from trademedia import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('media/',include('media.urls')),
    path('chart/',include('chart.urls')),
    path('', include('loginauth.urls')),  #追加
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

# if settigns.DEBUG:
#     urlpatterns += static(settings.IMAGE_URL,document_root = settings.IMAGE_ROOT)

chart/models.py
from django.db import models

# Create your models here.

loginauth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

media/models.py
# Create your models here.
import datetime

from django.db import models
from django.utils import timezone
from loginauth.models import User
# from django.contrib.auth.models import User



class Content(models.Model):
    post_id = models.AutoField(primary_key=True)
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True)
    picture = models.ImageField(
        upload_to="../images/images", blank=True, null=True)
    content = models.TextField(blank=False)
    title = models.CharField(max_length=20,blank=False)
    published_date = models.DateTimeField(blank=True,null=True)

    def __str__(self):
        return self.content

    # def was_published_recently(self):
    #     return self.create_time >= timezone.now() - datetime.timedelta(days=1)

loginauth/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User

class LoginForm(AuthenticationForm):
    """ログオンフォーム"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label
            
class UserCreateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #htmlの表示を変更可能にします
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'

    class Meta:
       model = User
       fields = ("username", "password1","password2", "email",)

media/forms.py
from django import forms
from .models import Content

class PostForm(forms.Form):
    title = forms.CharField()
    content = forms.CharField()
    picture = forms.ImageField()

chart/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

loginauth/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (LoginView, LogoutView)
from django.contrib.auth import login, authenticate
from django.views.generic import CreateView
from django.shortcuts import redirect
from loginauth.forms import LoginForm
from .models import User
from .forms import UserCreateForm

# Create your views here.
from django.http import HttpResponse

class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'loginauth/login.html'
    
class Logout(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    template_name = 'loginauth/login.html'

def signup(request):
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            print("検証に成功しました。データを保存します")
            form.save()
        else:
            print("検証に失敗したので、データを保存しません。検証に失敗した理由を次に表示します。")
            print(form.errors)
        return redirect('/login')
    return render(request, 'loginauth/create_user.html')

def redirect_view(request):
    response = redirect('/login')
    return response

media/views.py
from django.shortcuts import render, get_object_or_404
from loginauth.models import User
from .models import Content
from .forms import PostForm
from django.views.generic import ListView, CreateView
from django.views.generic.edit import CreateView
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import PostForm
from datetime import datetime
# from django.views.generic.edit import Forms
from django.urls import reverse
from django.conf.urls.static import static


def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")


@login_required
def profile(request):
    # user = get_object_or_404(User, pk=user_id)
    return HttpResponse(request.user.username)


class ContentsList(ListView):
    template_name = 'media/contents.html'


class PostView(CreateView):
    template_name = 'media/post.html'
    model = Content
    # Content.user_id =
    fields = ("title", "content", "picture")
    success_url = "/media/profile"

    def post(self, request, *args, **kwargs):
        """
        Handle POST requests: instantiate a form instance with the passed
        POST variables and then check if it's valid.
        """
        form = self.get_form()
        print(form)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.published_date = datetime.now()
        form.instance.author_id = self.request.user.id
        return super().form_valid(form)

templates/loginauth/create_user.html
<!DOCTYPE html>
<html lang="ja">

<head>
  <title>sign up</title>
  <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0" />

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
    integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

  <link type="text/css" rel="stylesheet" href="/static/css/froala_blocks.css">
</head>

<body>
  <section class="fdb-block">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-12 col-md-8 col-lg-8 col-xl-6">
          <div class="row">
            <div class="col text-center">
              <h1>Sign Up</h1>
              <p class="lead">サイトへようこそ。</p>
              <p>アカウントを持っていない方は作成してください。</p>
            </div>

          </div>

          <form action=" {%url 'loginauth:create_user' %}" method="post">
            {% csrf_token %}
            <div class="row align-items-center">
              <div class="col mt-4">
                <input type="text" class="form-control" name="username" placeholder="User Name">
              </div>
            </div>
            <div class="row align-items-center mt-4">
              <div class="col">
                <input type="email" class="form-control" name="email" placeholder="Email">
              </div>
            </div>

            <div class="row align-items-center mt-4">
              <div class="col">
                <input type="password" class="form-control" name="password1" placeholder="Password">
              </div>
              <div class="col">
                <input type="password" class="form-control" name="password2" placeholder="Confirm Password">
              </div>
            </div>
              <button type="submit" class="btn btn-primary mt-4 w-100" >Submit</button>
            <div class="text-left">
              <button class="btn btn-right btn-secondary mt-4" onclick="location.href='/login'">Log In</button>
            </div>
          </form>


        </div>
      </div>
    </div>
  </section>
</body>

</html>

templates/loginauth/login.html
<!DOCTYPE html>
<html>

<head>
  <title>login</title>
  <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0" />

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
    integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <link type="text/css" rel="stylesheet" href="/static/css/froala_blocks.css">
</head>

<body>
  <!-- Forms 5 -->
  <section class="fdb-block py-0">
    <div class="container py-5 my-5" style="background-image: url(/static/imgs/shapes/4.svg);">
      <div class=" row justify-content-end">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5 text-left">
          <div class="fdb-box">
            <div class="row">
              <div class="col">
                <h1>Log In</h1>
                <p class="lead">Right at the coast of the Semantics, a large language ocean. A small river named Duden.
                </p>
              </div>
            </div>
            <div class="row">
              {% if form.errors  %}
              <p>ユーザーID, パスワードが一致しません．</p>
              {% endif %}
              <form method="POST" action="{% url 'loginauth:login' %}">
                {% csrf_token %}
                <div class="col mt-4">
                  <label>User ID</label>
                  {{ form.username }}
                  {{ form.username.errors }}
                </div>
            </div>
            <div class="row mt-4">
              <div class="col">
                <label>PassWord</label>
                {{ form.password }}
                {{ form.password.errors }}
              </div>
            </div>
            <div class="row mt-4">
              <div class="col">
                <button class="btn btn-secondary" type="submit">Log In</button>
              </div>

              <div>
                <a href = "{% url 'loginauth:create_user'%}">アカウントを持っていない方はこちら</a>
              </div>
            </div>

            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</body>

</html>

templates/media/detail.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail</title>
</head>

<body>
    <h1>{{ object.title }}</h1>
    <p>{{ object.content }}</p>
    <p>Reporter: {{ username }}</p>
    <p>Published: {{ object.published_date }}</p>
    <!-- <p>{{object.picture }}</p> -->
    <!-- <p>{{MEDIA_URL}}</p> -->
    <img src="{{MEDIA_URL}}{{object.picture}}" width="200">
</body>

</html>

templates/media/post.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contents Post</title>
</head>

<body>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit">
    </form>
</body>

</html>

templates/media/top.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>PDFtoExcel</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/dist/css/AdminLTE.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/plugins/iCheck/square/blue.css' %}">

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
  <div class="login-box">
    <div class="login-logo">
      <b>TradeMedia</b>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
      <p class="login-box-msg"><b>ログオン画面</b></p>

      <form action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
          <div class="form-group has-feedback">
            {{ field }}
          </div>
        {% endfor %}
        <div class="row">

          {% for error in form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
              <p>{{ error }}</p>
            </div>
          {% endfor %}
          <!-- /.col -->
          <div class="col-xs-4">
            <button type="submit" class="btn btn-primary btn-block btn-flat">ログオン</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
    </div>
    <!-- /.login-box-body -->
  </div>
  <!-- /.login-box -->

  <!-- jQuery 3 -->
  <script src="{% static 'AdminLTE-2.4.12/bower_components/jquery/dist/jquery.min.js' %}"></script>
  <!-- Bootstrap 3.3.7 -->
  <script src="{% static 'AdminLTE-2.4.12/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  <!-- iCheck -->
  <script src="{% static 'AdminLTE-2.4.12/plugins/iCheck/icheck.min.js' %}"></script>
</body>
</html>

templates/media/usercontents.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contents</title>
</head>

<body>
    <h1>Articles</h1>
    <ul>
        {% for article in object_list %}
        <li>
            <a href="{% url 'media:detail' article.post_id%}">{{ article.title}}</a>
        </li>
        {% empty %}
        <li>No articles yet.</li>
        {% endfor %}
    </ul>
</body>

</html>